services:
  postgres:
    image: postgres:17-alpine
    container_name: ecommerce-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./microservices/deployments/docker/postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - ecommerce-network

  kafka:
    image: apache/kafka:4.0.0
    container_name: ecommerce-kafka
    restart: unless-stopped

    ports:
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

    networks:
      - ecommerce-network

  kafka-init:
    image: apache/kafka:4.0.0
    container_name: ecommerce-kafka-init

    depends_on:
      - kafka

    entrypoint: ["/bin/sh", "-c"]

    command:
      - |
        echo "Waiting for Kafka..."

        until /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --list >/dev/null 2>&1
        do
          sleep 2
        done

        echo "Kafka is ready."

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic payment.completed \
          --partitions 1 \
          --replication-factor 1

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic user.registered \
          --partitions 1 \
          --replication-factor 1

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic user.email.verification \
          --partitions 1 \
          --replication-factor 1

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic order.created \
          --partitions 1 \
          --replication-factor 1

        echo "Kafka topics initialized."

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --list

    networks:
      - ecommerce-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ecommerce-kafka-ui
    restart: unless-stopped

    ports:
      - "8081:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: ecommerce
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

    depends_on:
      - kafka

    networks:
      - ecommerce-network

volumes:
  postgres-data:

networks:
  ecommerce-network:
    driver: bridge