### Health
GET http://localhost:8080/health


### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Girma",
  "email": "girma@example.com",
  "password": "password123"
}

### Validation - Empty Name
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "",
  "email": "girma@example.com",
  "password": "password123"
}


### Validation - Invalid Email
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Girma",
  "email": "not-an-email",
  "password": "password123"
}


### Validation - Short Password
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Girma",
  "email": "another@example.com",
  "password": "123"
}


### Login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "girma@example.com",
  "password": "password123"
}

### Login - Wrong Password
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "girma@example.com",
  "password": "wrongpassword"
}

### Login - Unknown User
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "doesnotexist@example.com",
  "password": "password123"
}

### Get current user
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODczODk3NjksInVzZXJfaWQiOjF9.Yt9jKeD5LYzqIogXnvGkR38dc_bTYI3W9_xNL2BzrzU
